{
 "title": "Live Data Energy",
 "description": "easyhan.pt dashboard",
 "tags": [
  "HAN",
  "EDPBOX",
  "EMI"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Solar",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"1000-PV1\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"power\" and\r\n    r._field == \"value\"\r\n    )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)   \r\n  "
    }
   ]
  },
  {
   "title": "Solar",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"1000-PV1\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) =>\r\n    r._value != 0.0 and\r\n    r._measurement == \"pv_energy\" and\r\n    r._field == \"value\"\r\n  )\r\n  |> aggregateWindow(every: 1h, fn: max)\r\n  |> difference()\r\n  |> yield(name: \"sum\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Solar",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"1000-PV1\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) =>\r\n    r._value != 0.0 and\r\n    r._measurement == \"pv_energy\" and\r\n    r._field == \"value\"\r\n  )\r\n  |> aggregateWindow(every: 24h, fn: max)\r\n  |> difference()\r\n  |> yield(name: \"sum\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Voltage EB3",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"1000-EB3\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"vl1\" and\r\n    r._field == \"value\" and\r\n    r.device == \"edpbox3\" and\r\n    r.sensor == \"eb3\" and\r\n    r._value > 150\r\n    )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)   \r\n  "
    },
    {
     "query": "from(bucket: \"1000-EB3\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"vl2\" and\r\n    r._field == \"value\" and\r\n    r.device == \"edpbox3\" and\r\n    r.sensor == \"eb3\"and\r\n    r._value > 150\r\n  )\r\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)   \r\n  "
    },
    {
     "query": "from(bucket: \"1000-EB3\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"vl3\" and\r\n    r._field == \"value\" and\r\n    r.device == \"edpbox3\" and\r\n    r.sensor == \"eb3\"and\r\n    r._value > 150\r\n  )\r\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)   \r\n  "
    }
   ]
  },
  {
   "title": "Voltage EB1",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"1000-EB1\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"vl1\" and\r\n    r._field == \"value\"\r\n    )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)   \r\n  "
    }
   ]
  }
 ]
}