{
 "title": "Live Data Environment",
 "description": "easyhan.pt dashboard",
 "tags": [
  "HAN",
  "EDPBOX",
  "EMI"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Water Level",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"1000-HA1\")\r\n  |> range(start: -2d)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"sensor.water_level_4_20ma\" and\r\n    r._field == \"value\"\r\n    )\r\n  |> aggregateWindow(every: 10m, fn: mean, createEmpty: true)   \r\n  "
    }
   ]
  },
  {
   "title": "Atmospheric Pressure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"1000-HA1\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"sensor.bme280_pressure\" and\r\n    r._field == \"value\"\r\n    )\r\n  |> aggregateWindow(every: 30m, fn: max, createEmpty: true)   \r\n  "
    }
   ]
  },
  {
   "title": "Outdoor CO2",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"1000-HA1\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"sensor.t45_scd41_co2\" and\r\n    r._field == \"value\"\r\n    )\r\n  |> aggregateWindow(every: 30m, fn: mean, createEmpty: true)   \r\n  "
    }
   ]
  }
 ]
}