{
 "title": "HAN Lite EB3",
 "description": "easyhan.pt dashboard\nInfluxdb V2 / Flux",
 "tags": [
  "HAN",
  "EDPBOX",
  "EMI"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "HanBucket", "query": "${VAR_HANBUCKET}" },
   { "name": "HanDevice", "query": "${VAR_HANDEVICE}" },
   { "name": "HanSensor", "query": "${VAR_HANSENSOR}" }
  ]
 },
 "panels": [
  {
   "title": "Active Power Import",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${HanBucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> last()\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"api\" and\r\n    r._field == \"value\" and\r\n    r.device == \"${HanDevice}\" and\r\n    r.sensor == \"${HanSensor}\"\r\n  )"
    },
    {
     "query": "from(bucket: \"${HanBucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> last()\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"api1\" and\r\n    r._field == \"value\" and\r\n    r.device == \"${HanDevice}\" and\r\n    r.sensor == \"${HanSensor}\"\r\n  )"
    },
    {
     "query": "from(bucket: \"${HanBucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> last()\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"api2\" and\r\n    r._field == \"value\" and\r\n    r.device == \"${HanDevice}\" and\r\n    r.sensor == \"${HanSensor}\"\r\n  )"
    },
    {
     "query": "from(bucket: \"${HanBucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> last()\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"api3\" and\r\n    r._field == \"value\" and\r\n    r.device == \"${HanDevice}\" and\r\n    r.sensor == \"${HanSensor}\"\r\n  )"
    }
   ]
  },
  {
   "title": "Active Power Export",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${HanBucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> last()\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"ape\" and\r\n    r._field == \"value\" and\r\n    r.device == \"${HanDevice}\" and\r\n    r.sensor == \"${HanSensor}\"\r\n  )"
    },
    {
     "query": "from(bucket: \"${HanBucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> last()\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"ape1\" and\r\n    r._field == \"value\" and\r\n    r.device == \"${HanDevice}\" and\r\n    r.sensor == \"${HanSensor}\"\r\n  )"
    },
    {
     "query": "from(bucket: \"${HanBucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> last()\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"ape2\" and\r\n    r._field == \"value\" and\r\n    r.device == \"${HanDevice}\" and\r\n    r.sensor == \"${HanSensor}\"\r\n  )"
    },
    {
     "query": "from(bucket: \"${HanBucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> last()\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"ape3\" and\r\n    r._field == \"value\" and\r\n    r.device == \"${HanDevice}\" and\r\n    r.sensor == \"${HanSensor}\"\r\n  )"
    }
   ]
  },
  {
   "title": "Total Energy",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"${HanBucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"tei\" and\r\n    r._field == \"value\" and\r\n    r._value != 0.0 and\r\n    r.device == \"${HanDevice}\" and\r\n    r.sensor == \"${HanSensor}\"\r\n  )\r\n  |> aggregateWindow(every: 1h, fn: max)\r\n  |> difference()\r\n  |> yield(name: \"sum\")\r\n\r\n"
    },
    {
     "query": "from(bucket: \"${HanBucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"tee\" and\r\n    r._field == \"value\" and\r\n    r._value != 0.0 and\r\n    r.device == \"${HanDevice}\" and\r\n    r.sensor == \"${HanSensor}\"\r\n  )\r\n  |> aggregateWindow(every: 1h, fn: max)\r\n  |> difference()\r\n  |> yield(name: \"sum\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Active Power Import",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"${HanBucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"api\" and\r\n    r._field == \"value\" and\r\n    r.device == \"${HanDevice}\" and\r\n    r.sensor == \"${HanSensor}\"\r\n  )"
    },
    {
     "query": "from(bucket: \"${HanBucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"api1\" and\r\n    r._field == \"value\"\r\n  )"
    },
    {
     "query": "from(bucket: \"${HanBucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"api2\" and\r\n    r._field == \"value\"\r\n  )"
    },
    {
     "query": "from(bucket: \"${HanBucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"api3\" and\r\n    r._field == \"value\"\r\n  )"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"${HanBucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"vl1\" and\r\n    r._field == \"value\" and\r\n    r.device == \"${HanDevice}\" and\r\n    r.sensor == \"${HanSensor}\"\r\n  )"
    },
    {
     "query": "from(bucket: \"${HanBucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"vl2\" and\r\n    r._field == \"value\" and\r\n    r.device == \"${HanDevice}\" and\r\n    r.sensor == \"${HanSensor}\"\r\n  )"
    },
    {
     "query": "from(bucket: \"${HanBucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"vl3\" and\r\n    r._field == \"value\" and\r\n    r.device == \"${HanDevice}\" and\r\n    r.sensor == \"${HanSensor}\"\r\n  )"
    }
   ]
  },
  {
   "title": "Total Energy",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"${HanBucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"tei\" and\r\n    r._field == \"value\" and\r\n    r._value != 0.0 and\r\n    r.device == \"${HanDevice}\" and\r\n    r.sensor == \"${HanSensor}\"\r\n  )\r\n  |> aggregateWindow(every: 24h, fn: max)\r\n  |> difference()\r\n  |> yield(name: \"sum\")\r\n\r\n"
    },
    {
     "query": "from(bucket: \"${HanBucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"tee\" and\r\n    r._field == \"value\" and\r\n    r._value != 0.0 and\r\n    r.device == \"${HanDevice}\" and\r\n    r.sensor == \"${HanSensor}\"\r\n  )\r\n  |> aggregateWindow(every: 24h, fn: max)\r\n  |> difference()\r\n  |> yield(name: \"sum\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Total Energy",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"${HanBucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"tei\" and\r\n    r._field == \"value\" and\r\n    r._value != 0.0 and\r\n    r.device == \"${HanDevice}\" and\r\n    r.sensor == \"${HanSensor}\"\r\n  )\r\n  |> aggregateWindow(every: 1d, fn: max)\r\n  |> difference()\r\n  |> yield(name: \"sum\")\r\n\r\n"
    },
    {
     "query": "from(bucket: \"${HanBucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"tee\" and\r\n    r._field == \"value\" and\r\n    r._value != 0.0 and\r\n    r.device == \"${HanDevice}\" and\r\n    r.sensor == \"${HanSensor}\"\r\n  )\r\n  |> aggregateWindow(every: 1d, fn: max)\r\n  |> difference()\r\n  |> yield(name: \"sum\")\r\n\r\n"
    }
   ]
  }
 ]
}