# Mosquitto Addon:
# ...
# customize:
#  active: true
#  folder: mosquitto
# ...

# File:
# /share/mosquitto/ttn.conf

connection ttn
bridge_protocol_version mqttv311
try_private false
address eu1.cloud.thethings.network:1883
remote_username nikito-app@ttn
remote_password ****key***
remote_clientid easyhan-ttn-in
topic v3/nikito-app@ttn/# in 0 home/ ""

# EOF
