# Pulse Counter

substitutions:
  dev: Pulse
  name: pulse

esphome:
  name: ${name}
  project:
    name: easyhan.pulse
    version: "1.08"
  on_boot:
    priority: 1000
    then:
      - lambda: |-
          pinMode(39, OUTPUT);
          digitalWrite(39, LOW);

dashboard_import:
  package_import_url: github://nikito7/easyhan/esphome/Pulse-Basic.yaml@dev
  import_full_config: true

esp32:
  board: esp32-s3-devkitc-1 # N8
  framework:
    type: arduino
  flash_size: 8MB
  variant: esp32s3

wifi:
  output_power: 15db
  #use_address: 10.1.0.39

  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #password: edpbox123

  ap:
    ssid: "Easy-HAN-${dev}"
    password: edpbox123
    ap_timeout: 20s # change me

captive_portal:

###

###

#esp32_ble_tracker:
#bluetooth_proxy:

###

web_server:
  local: true
  version: 3
  
logger:
  #level: debug
  level: verbose

api:
  reboot_timeout: 30min

ota:
  - platform: esphome

time:
  - platform: homeassistant
    id: esptime

## ## ##

button:

  - platform: restart
    name: "${dev} ESP Restart"

## ## ##

sensor:

  - platform: pulse_counter
    name: "${dev} Counter Basic"
    id: pulse_counter_id
    pin:
      number: 18
      inverted: true
      mode:
        input: true
        pullup: true
    count_mode:
      rising_edge: DISABLE
      falling_edge: INCREMENT
    use_pcnt: false
    internal_filter: 100ms
    update_interval: 10s
    total:
      name: "${dev} Counter Basic Total"
      filters:
        - multiply: 0.001
      accuracy_decimals: 3
      device_class: water
      state_class: total_increasing
      unit_of_measurement: "m³"

###

  - platform: template
    name: "${dev} Adc In"
    id: adc_in_v
    accuracy_decimals: 2
    device_class: voltage
    unit_of_measurement: "V"
    state_class: measurement

  - platform: adc
    name: "${dev} Adc In raw" # ESP32-S3 PCB
    raw: true
    pin: 1
    attenuation: 0dB
    samples: 8
    accuracy_decimals: 0
    device_class: ""
    unit_of_measurement: "raw"
    icon: mdi:information
    state_class: measurement
    on_value:
      then:
        - lambda: id(adc_in_v).publish_state(x/257.2580645161);

###

  - platform: template
    name: "${dev} ESP Free Heap"
    lambda: |-
      // arduino
      float heap = ESP.getFreeHeap();
      // idf
      //float heap = esp_get_free_heap_size();
      return heap / 1024.0;
    unit_of_measurement: "kB"
    icon: mdi:chip
    state_class: measurement
    entity_category: diagnostic

  - platform: wifi_signal
    name: "${dev} ESP Signal"
    unit_of_measurement: "dB"
    state_class: measurement
    entity_category: diagnostic

  - platform: uptime
    name: "${dev} ESP Uptime"
    filters:
      - lambda: return x/3600;
    unit_of_measurement: "h"
    accuracy_decimals: 1
    device_class: ""
    entity_category: diagnostic

### ### ###


### ### ###

text_sensor:

  - platform: version
    name: "${dev} ESPHome Version"
    hide_timestamp: true
    entity_category: diagnostic


###

#######
# eof #
#######
