# Wmbus V5 (ESPHome >= 2026.7.2)
# Chip: CC1101 / LoRa
# Meter: Izar / Arrow
# IDF Framework
# Tested:
# CC + Arrow OK.
# LoRa + Izar OK.

external_components:
  - source: github://nikito7/__wmbus@arrow-v5-main
  #- source: github://SzczepanLeon/esphome-components@main
  #- source: github://nikito7/__wmbus@arrow-v5
    refresh: 0d
    components: [wmbus_common, wmbus_radio, wmbus_meter]

substitutions:
  dev: WMBUS
  name: wmbus

esphome:
  name: ${name}
  friendly_name: ${dev}
  project:
    name: easyhan.wmbus
    version: "5.12"

dashboard_import:
  package_import_url: github://nikito7/easyhan/esphome/wmbus-v5.yaml@dev
  import_full_config: true

esp32:
  # board: heltec_wifi_lora_32_V2
  board: esp32-s3-devkitc-1
  flash_size: 8MB
  framework:
    type: esp-idf

wifi:
  output_power: 15db
  #use_address: 10.1.0.39

  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #password: edpbox123

  ap:
    ssid: "Easy-HAN-${dev}"
    password: edpbox123


captive_portal:

###

#esp32_ble_tracker:
#bluetooth_proxy:

###

web_server:
  local: true
  version: 3
  
logger:
  id: component_logger
  #level: debug
  level: verbose

api:
  reboot_timeout: 33min

ota:
  - platform: esphome

time:
  - platform: homeassistant
    id: esptime

button:
  - platform: restart
    name: "ESP Restart"

###

spi:
  # --- cc ---
  clk_pin: GPIO35
  mosi_pin: GPIO37
  miso_pin: GPIO38
  # --- lora ---
  #clk_pin:
  #  number: GPIO5
  #  ignore_strapping_warning: true
  #mosi_pin: GPIO27
  #miso_pin: GPIO19

wmbus_common:
    drivers: all

wmbus_radio:
  # ---
  radio_type: CC1101
  cs_pin: GPIO36
  irq_pin: GPIO33 # gdo0
  frequency: 868.95MHz
  # ---
  #radio_type: SX1276
  #cs_pin: GPIO18
  #reset_pin: GPIO14
  #irq_pin: GPIO35
  on_frame:
    - then:
        - logger.log:
            format: "RSSI: %ddBm T: %s (%d)"
            args: [ frame->rssi(), frame->as_hex().c_str(), frame->data().size() ]
        - lambda: id(meter_rssi).publish_state(frame->rssi());
    - then:
        - repeat:
            count: 3
            then:
              - output.turn_on: status_led
              - delay: 100ms
              - output.turn_off: status_led
              - delay: 100ms


wmbus_meter:
  - id: water_meter
    meter_id: 0x22334455
    #meter_id: !secret meter_id
    type: izar
    key: "00000000000000000000000000000000"
    #key: !secret meter_key
    mode: 
      - T1

output:
  - platform: gpio
    id: status_led
    pin: GPIO39
    #pin: GPIO25


###

sensor:

## ## ##

##
  - platform: template
    name: "Test Izar Signal"
    id: meter_rssi
    accuracy_decimals: 0
    unit_of_measurement: "dBm"
    device_class: "signal_strength"
    state_class: "measurement"

##

  - platform: wmbus_meter
    parent_id: water_meter
    name: "Test Izar Total"
    field: "total_m3"
    accuracy_decimals: 3
    unit_of_measurement: "m³"
    device_class: "water"
    state_class: "total_increasing"
    icon: "mdi:counter"

## ## ##

  - platform: template
    name: "Adc In"
    id: adc_in_v
    accuracy_decimals: 2
    device_class: voltage
    unit_of_measurement: "V"
    state_class: measurement

  - platform: adc
    name: "Adc In raw" # ESP32-S3 PCB
    raw: true
    pin: 1
    attenuation: 0dB
    samples: 8
    accuracy_decimals: 0
    device_class: ""
    unit_of_measurement: "raw"
    icon: mdi:information
    state_class: measurement
    on_value:
      then:
        - lambda: id(adc_in_v).publish_state(x/257.2580645161);

###

  - platform: template
    name: "ESP Free Heap"
    lambda: |-
      // arduino
      //float heap = ESP.getFreeHeap();
      // idf
      float heap = esp_get_free_heap_size();
      return heap / 1024.0;
    unit_of_measurement: "kB"
    icon: mdi:chip
    state_class: measurement
    entity_category: diagnostic

  - platform: wifi_signal
    name: "ESP Signal"
    unit_of_measurement: "dB"
    state_class: measurement
    entity_category: diagnostic

  - platform: uptime
    name: "ESP Uptime"
    filters:
      - lambda: return x/3600;
    unit_of_measurement: "h"
    accuracy_decimals: 1
    device_class: ""
    entity_category: diagnostic

### ### ###


### ### ###

text_sensor:

  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true
    entity_category: diagnostic


###

#######
# eof #
#######
